server:
  port: 8089

spring:
  # DataSource Configuration qui utilise MySQL
  datasource:
    url: jdbc:mysql://localhost:4444/operis_project?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Hibernate Configuration jpa pour la gestion des entit√©s
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

code:
  secret: mAvsZD2KqE2Kv6VpF+VkN1P3PT+2uq5z0g2Zx-eF0StSc=

logging:
  level:
    root: INFO
    com.operis: DEBUG